BasketShop/BasketShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('payment/', include('payment.urls')),
    path('', include('shop.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

BasketShop/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('get_cart/', views.get_cart, name='get_cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
]

BasketShop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.create_order, name='create_order'),
]

BasketShop/cart/views.py
from django.conf import settings
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST

from .cart import Cart
from shop.models import Product


# Create your views here.
def get_cart(request):
    cart = Cart(request)
    data = cart.serialize()

    # cart_data = list(cart)
    return JsonResponse({'cart': data})

@require_POST
def add_to_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product)
    return JsonResponse({'cartCount': str(len(cart))})

@require_POST
def remove_from_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return JsonResponse({'success': True, 'cartCount': str(len(cart))})

BasketShop/templates/cart/cart.html
<div id="cart-modal" class="cart-modal">
    <div class="cart-content">
        <!-- Крестик в виде иконки -->
        <span id="close-cart" class="close-icon">✖</span>

        <!-- Заголовок с отступом -->
        <h2 class="cart-title">Корзина</h2>
        <div id="cart-items"></div>

        <!-- Кнопка "Заказать" -->
        <a href="{% url 'orders:create_order' %}" class="btn-link">
            <button class="btn btn-create-order">Заказать</button>
        </a>
    </div>
</div>